// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vytzegqklhijxbqbmbop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5dHplZ3FrbGhpanhicWJtYm9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTIzNDgsImV4cCI6MjA2NzQ2ODM0OH0.j7697uPrLZrQXgKpb5FCAIvc4_67oeCb_V0nudqDRDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});